# Generated by Django 2.1.4 on 2019-01-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ruc_usuario',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
