# Generated by Django 2.1.5 on 2019-01-23 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto_ruc_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ruc_usuario',
        ),
    ]
