# Generated by Django 2.1.4 on 2019-02-04 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0003_remove_establecimiento_ruc_usuario'),
        ('producto', '0003_remove_producto_ruc_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='establecimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='establecimiento.Establecimiento'),
        ),
    ]
