# Generated by Django 2.1.4 on 2019-02-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_producto_establecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad',
            field=models.CharField(choices=[('barriles', 'barriles'), ('cajas', 'cajas'), ('galones', 'galones'), ('gramos', 'gramos'), ('kilogramos', 'kilogramos'), ('latas', 'latas'), ('libras', 'libras'), ('litros', 'litros'), ('metros', 'metros'), ('metros cúbicos', 'metros cúbicos'), ('millares', 'millares'), ('toneladas', 'toneladas'), ('toneladas largas', 'toneladas largas'), ('toneladas métricas', 'toneladas métricas'), ('unidades', 'unidades')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
