# Generated by Django 2.1.4 on 2019-02-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_producto_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad',
            field=models.CharField(choices=[('barriles', 'barriles'), ('cajas', 'cajas'), ('galones', 'galones'), ('gramos', 'gramos'), ('kilogramos', 'kilogramos'), ('latas', 'latas'), ('libras', 'libras'), ('litros', 'litros'), ('metros', 'metros'), ('metros cúbicos', 'metros cúbicos'), ('millares', 'millares'), ('toneladas cortas', 'toneladas cortas'), ('toneladas largas', 'toneladas largas'), ('toneladas métricas', 'toneladas métricas'), ('unidades', 'unidades')], max_length=50),
        ),
    ]
