# Generated by Django 2.1.5 on 2019-01-23 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cliente',
        ),
    ]
