# Generated by Django 2.1.4 on 2019-01-09 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factura', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('factura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='factura.Factura')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='producto.Producto')),
            ],
        ),
    ]
