# Generated by Django 2.1.4 on 2019-01-07 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(blank=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('numero_factura', models.CharField(max_length=12)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.Cliente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='usuario.Usuario')),
            ],
        ),
    ]
