# Generated by Django 2.1.4 on 2019-02-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
