# Generated by Django 2.1.4 on 2019-01-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='ruc_usuario',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='tipo_establecimiento',
            field=models.CharField(choices=[('Domicilio fiscal', 'Domicilio Fiscal'), ('Anexo', 'Anexo')], max_length=50),
        ),
    ]
