# Generated by Django 2.1.4 on 2019-01-17 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0002_auto_20190117_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establecimiento',
            name='ruc_usuario',
        ),
    ]
